[build]
  command = """
    if [ -d "netlify/functions" ] && [ "$(ls -A netlify/functions 2>/dev/null)" ]; then
      echo "Building Netlify functions..."
      # Add function build commands if needed
    else
      echo "No functions to build"
    fi
  """
  
  # Only build when functions or netlify config changes
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- netlify/ functions/ netlify.toml && exit 0 || exit 1"

[functions]
  directory = "netlify/functions"
