[build]
  publish = "public"
  command = "echo 'Using GitHub Actions for build - skipping Netlify build'"
  
  # Only build if functions or config files change, skip content-only changes
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- netlify/ functions/ netlify.toml hugo.toml config.toml config.yaml || exit 0"

[functions]
  directory = "netlify/functions"
