[build]
  command = "go run main.go"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/cms"
  to = "/.netlify/functions/cms"
  status = 200

[[redirects]]
  from = "/cms/*"
  to = "/.netlify/functions/cms/:splat"
  status = 200

[[redirects]]
  from = "/thoughts"
  to = "/links"
  status = 301

[[redirects]]
  from = "/thoughts/*"
  to = "/links/:splat"
  status = 301

[[redirects]]
  from = "/type/thoughts/rss.xml"
  to = "/type/links/rss.xml"
  status = 301
