// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package libsqlssg

import (
	"database/sql"
)

type Author struct {
	ID       int64        `json:"id"`
	Username string       `json:"username"`
	Name     string       `json:"name"`
	Password string       `json:"password"`
	IsAdmin  sql.NullBool `json:"is_admin"`
}

type Post struct {
	ID          string          `json:"id"`
	TypeID      string          `json:"type_id"`
	Title       string          `json:"title"`
	Slug        string          `json:"slug"`
	Content     string          `json:"content"`
	Excerpt     sql.NullString  `json:"excerpt"`
	Status      sql.NullString  `json:"status"`
	IsFeatured  sql.NullFloat64 `json:"is_featured"`
	Tags        sql.NullString  `json:"tags"`
	Metadata    sql.NullString  `json:"metadata"`
	CreatedAt   sql.NullFloat64 `json:"created_at"`
	UpdatedAt   sql.NullFloat64 `json:"updated_at"`
	PublishedAt sql.NullFloat64 `json:"published_at"`
}
