// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package libsqlssg

import (
	"database/sql"
)

type Author struct {
	ID       int64        `json:"id"`
	Username string       `json:"username"`
	Name     string       `json:"name"`
	Password string       `json:"password"`
	IsAdmin  sql.NullBool `json:"is_admin"`
}

type Post struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	Slug      string       `json:"slug"`
	Body      string       `json:"body"`
	Metadata  string       `json:"metadata"`
	Deleted   sql.NullBool `json:"deleted"`
	CreatedAt interface{}  `json:"created_at"`
	UpdatedAt interface{}  `json:"updated_at"`
	AuthorID  int64        `json:"author_id"`
}
