// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package libsqlssg

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (username, name, password)
VALUES (?, ?, ?) RETURNING id
`

type CreateAuthorParams struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Username, arg.Name, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, type_id, title, slug, content, metadata, tags, status) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, type_id, title, slug, content, metadata, tags, status
`

type CreatePostParams struct {
	ID       string         `json:"id"`
	TypeID   string         `json:"type_id"`
	Title    string         `json:"title"`
	Slug     string         `json:"slug"`
	Content  string         `json:"content"`
	Metadata sql.NullString `json:"metadata"`
	Tags     sql.NullString `json:"tags"`
	Status   sql.NullString `json:"status"`
}

type CreatePostRow struct {
	ID       string         `json:"id"`
	TypeID   string         `json:"type_id"`
	Title    string         `json:"title"`
	Slug     string         `json:"slug"`
	Content  string         `json:"content"`
	Metadata sql.NullString `json:"metadata"`
	Tags     sql.NullString `json:"tags"`
	Status   sql.NullString `json:"status"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.TypeID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Metadata,
		arg.Tags,
		arg.Status,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Metadata,
		&i.Tags,
		&i.Status,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
UPDATE posts SET status = 'deleted' WHERE slug = ?
`

func (q *Queries) DeletePost(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deletePost, slug)
	return err
}

const ensurePostType = `-- name: EnsurePostType :exec
INSERT OR IGNORE INTO post_types (id, name, slug)
VALUES (?, ?, ?)
`

type EnsurePostTypeParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) EnsurePostType(ctx context.Context, arg EnsurePostTypeParams) error {
	_, err := q.db.ExecContext(ctx, ensurePostType, arg.ID, arg.Name, arg.Slug)
	return err
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT id, type_id, title, slug, content, metadata, tags, status, created_at, updated_at FROM posts WHERE status != 'deleted'
`

type GetAllPostsRow struct {
	ID        string          `json:"id"`
	TypeID    string          `json:"type_id"`
	Title     string          `json:"title"`
	Slug      string          `json:"slug"`
	Content   string          `json:"content"`
	Metadata  sql.NullString  `json:"metadata"`
	Tags      sql.NullString  `json:"tags"`
	Status    sql.NullString  `json:"status"`
	CreatedAt sql.NullFloat64 `json:"created_at"`
	UpdatedAt sql.NullFloat64 `json:"updated_at"`
}

func (q *Queries) GetAllPosts(ctx context.Context) ([]GetAllPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPostsRow
	for rows.Next() {
		var i GetAllPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Metadata,
			&i.Tags,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, username, name, password, is_admin FROM authors WHERE id = ?
`

func (q *Queries) GetAuthorByID(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, type_id, title, slug, content, metadata, tags, status FROM posts WHERE slug = ? AND status != 'deleted'
`

type GetPostBySlugRow struct {
	ID       string         `json:"id"`
	TypeID   string         `json:"type_id"`
	Title    string         `json:"title"`
	Slug     string         `json:"slug"`
	Content  string         `json:"content"`
	Metadata sql.NullString `json:"metadata"`
	Tags     sql.NullString `json:"tags"`
	Status   sql.NullString `json:"status"`
}

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i GetPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Metadata,
		&i.Tags,
		&i.Status,
	)
	return i, err
}

const getPostsBySlugType = `-- name: GetPostsBySlugType :many
SELECT id, type_id, title, slug, content, metadata, tags, status FROM posts WHERE slug = ? AND status != 'deleted'
`

type GetPostsBySlugTypeRow struct {
	ID       string         `json:"id"`
	TypeID   string         `json:"type_id"`
	Title    string         `json:"title"`
	Slug     string         `json:"slug"`
	Content  string         `json:"content"`
	Metadata sql.NullString `json:"metadata"`
	Tags     sql.NullString `json:"tags"`
	Status   sql.NullString `json:"status"`
}

func (q *Queries) GetPostsBySlugType(ctx context.Context, slug string) ([]GetPostsBySlugTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsBySlugType, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsBySlugTypeRow
	for rows.Next() {
		var i GetPostsBySlugTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Metadata,
			&i.Tags,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, password, is_admin FROM authors WHERE username = ?
`

type GetUserRow struct {
	ID       int64        `json:"id"`
	Name     string       `json:"name"`
	Password string       `json:"password"`
	IsAdmin  sql.NullBool `json:"is_admin"`
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors SET name = ?, password = ?, is_admin = ? WHERE id = ? RETURNING id, username, name, password, is_admin
`

type UpdateAuthorParams struct {
	Name     string       `json:"name"`
	Password string       `json:"password"`
	IsAdmin  sql.NullBool `json:"is_admin"`
	ID       int64        `json:"id"`
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, updateAuthor,
		arg.Name,
		arg.Password,
		arg.IsAdmin,
		arg.ID,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts SET title = ?, content = ?, metadata = ?, tags = ? WHERE slug = ?
`

type UpdatePostParams struct {
	Title    string         `json:"title"`
	Content  string         `json:"content"`
	Metadata sql.NullString `json:"metadata"`
	Tags     sql.NullString `json:"tags"`
	Slug     string         `json:"slug"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Content,
		arg.Metadata,
		arg.Tags,
		arg.Slug,
	)
	return err
}
