name: Deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Cache markata cache
        uses: actions/cache@v3
        with:
          path: .markata.cache
          key: ${{ runner.os }}-${{ hashFiles('markata.toml') }}-${{ steps.date.outputs.date }}-markata
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('markata.toml') }}-markata

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.16'

      - name: Install markata dependencies
        run: pip install -r requirements.txt

      - name: Run markata
        run: markata build

      - name: sw-version
        run: |
          export checksum=$(checksumdir markout)
          cat static/sw.js | envsubst > markout/sw.js

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: markout
          build_dir: markout
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}