name: Deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set up Golang 1.23.3
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3

      - name: install dependencies
        run: go mod download && go mod tidy

      - name: build ssg
        run: go run main.go

      - name: GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
          jekyll: false
